import { IWallpaper } from '~/types/Wallpaper';

export const allWallpapers: IWallpaper[] = [
	{
		id: 1,
		filename: '01.jpg',
		src: 'https://gif.plaza.one/01.jpg',
		video_src: 'https://gif.plaza.one/mp4/01.mp4',
		author: 'madeonish',
		author_link: 'http://madeonish.tumblr.com/',
		source: 'Original',
		source_link: '',
		num: '01',
	},
	{
		id: 2,
		filename: '02.gif',
		src: 'https://gif.plaza.one/02.gif',
		video_src: 'https://gif.plaza.one/mp4/02.mp4',
		author: 'MAX CAPACITY',
		author_link:
			'https://24.media.tumblr.com/07d610f83d41d2339c827c748bc11728/tumblr_n3kw2iLJen1qzpy7ko1_500.gif',
		source: '',
		source_link: '',
		num: '02',
	},
	{
		id: 3,
		filename: '03.gif',
		src: 'https://gif.plaza.one/03.gif',
		video_src: 'https://gif.plaza.one/mp4/03.mp4',
		author: 'Mark Ferrari',
		author_link: 'http://markferrari.com/art/8bit-game-art/',
		source: 'Original',
		source_link: '',
		num: '03',
	},
	{
		id: 4,
		filename: '04.gif',
		src: 'https://gif.plaza.one/04.gif',
		video_src: 'https://gif.plaza.one/mp4/04.mp4',
		author: 'KidMoGraph',
		author_link: 'https://www.kidmograph.com/personal',
		source: 'Original',
		source_link: '',
		num: '04',
	},
	{
		id: 5,
		filename: '05.gif',
		src: 'https://gif.plaza.one/05.gif',
		video_src: 'https://gif.plaza.one/mp4/05.mp4',
		author: '',
		author_link: '',
		source: 'Ghost in the Shell: S.A.C.',
		source_link:
			'https://myanimelist.net/anime/467/Ghost_in_the_Shell__Stand_Alone_Complex',
		num: '05',
	},
	{
		id: 6,
		filename: '06.gif',
		src: 'https://gif.plaza.one/06.gif',
		video_src: 'https://gif.plaza.one/mp4/06.mp4',
		author: '',
		author_link: '',
		source: 'Burn Up! W',
		source_link: 'https://myanimelist.net/anime/769/Burn_Up_W',
		num: '06',
	},
	{
		id: 7,
		filename: '07.gif',
		src: 'https://gif.plaza.one/07.gif',
		video_src: 'https://gif.plaza.one/mp4/07.mp4',
		author: 'silverchrome7777',
		author_link: 'https://www.deviantart.com/silverchrome7777',
		source: 'speak of the devil and it delivers',
		source_link: '',
		num: '07',
	},
	{
		id: 8,
		filename: '08.gif',
		src: 'https://gif.plaza.one/08.gif',
		video_src: 'https://gif.plaza.one/mp4/08.mp4',
		author: 'KidMoGraph',
		author_link: 'https://www.kidmograph.com/personal',
		source: 'Original',
		source_link: '',
		num: '08',
	},
	{
		id: 9,
		filename: '09.gif',
		src: 'https://gif.plaza.one/09.gif',
		video_src: 'https://gif.plaza.one/mp4/09.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '09',
	},
	{
		id: 10,
		filename: '10.gif',
		src: 'https://gif.plaza.one/10.gif',
		video_src: 'https://gif.plaza.one/mp4/10.mp4',
		author: 'decadot',
		author_link:
			'https://decadot.tumblr.com/post/117858729431/ghost-chaser-densei-super-famicom-banpresto',
		source: 'Ghost Chaser Densei',
		source_link: 'https://en.wikipedia.org/wiki/Denjin_Makai',
		num: '10',
	},
	{
		id: 11,
		filename: '11.gif',
		src: 'https://gif.plaza.one/11.gif',
		video_src: 'https://gif.plaza.one/mp4/11.mp4',
		author: '',
		author_link: '',
		source: 'Devilman: Tanjou-hen',
		source_link: 'https://myanimelist.net/anime/2354/Devilman__Tanjou-hen',
		num: '11',
	},
	{
		id: 12,
		filename: '12.gif',
		src: 'https://gif.plaza.one/12.gif',
		video_src: 'https://gif.plaza.one/mp4/12.mp4',
		author: '',
		author_link: '',
		source: 'Megazone 23',
		source_link: 'https://myanimelist.net/anime/1935/Megazone_23',
		num: '12',
	},
	{
		id: 13,
		filename: '13.gif',
		src: 'https://gif.plaza.one/13.gif',
		video_src: 'https://gif.plaza.one/mp4/13.mp4',
		author: '',
		author_link: '',
		source: 'Bubblegum Crisis',
		source_link: 'https://myanimelist.net/anime/1347/Bubblegum_Crisis',
		num: '13',
	},
	{
		id: 14,
		filename: '14.gif',
		src: 'https://gif.plaza.one/14.gif',
		video_src: 'https://gif.plaza.one/mp4/14.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '14',
	},
	{
		id: 15,
		filename: '15.gif',
		src: 'https://gif.plaza.one/15.gif',
		video_src: 'https://gif.plaza.one/mp4/15.mp4',
		author: 'badcodec',
		author_link: 'https://giphy.com/badcodec',
		source: '',
		source_link: '',
		num: '15',
	},
	{
		id: 16,
		filename: '16.gif',
		src: 'https://gif.plaza.one/16.gif',
		video_src: 'https://gif.plaza.one/mp4/16.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '16',
	},
	{
		id: 17,
		filename: '17.gif',
		src: 'https://gif.plaza.one/17.gif',
		video_src: 'https://gif.plaza.one/mp4/17.mp4',
		author: 'Rebloggy',
		author_link: 'http://rebloggy.com/post/my-gif-ningen-shikaku/13124307676 ',
		source: 'No Longer Human',
		source_link: 'https://en.wikipedia.org/wiki/No_Longer_Human#Adaptations',
		num: '17',
	},
	{
		id: 18,
		filename: '18.gif',
		src: 'https://gif.plaza.one/18.gif',
		video_src: 'https://gif.plaza.one/mp4/18.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '18',
	},
	{
		id: 19,
		filename: '19.gif',
		src: 'https://gif.plaza.one/19.gif',
		video_src: 'https://gif.plaza.one/mp4/19.mp4',
		author: '',
		author_link: '',
		source: 'Kotonoha no Niwa',
		source_link: 'https://myanimelist.net/anime/16782/Kotonoha_no_Niwa',
		num: '19',
	},
	{
		id: 20,
		filename: '20.gif',
		src: 'https://gif.plaza.one/20.gif',
		video_src: 'https://gif.plaza.one/mp4/20.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '20',
	},
	{
		id: 21,
		filename: '21.gif',
		src: 'https://gif.plaza.one/21.gif',
		video_src: 'https://gif.plaza.one/mp4/21.mp4',
		author: '',
		author_link: '',
		source: 'Gake no Ue no Ponyo',
		source_link: 'https://myanimelist.net/anime/2890/Gake_no_Ue_no_Ponyo',
		num: '21',
	},
	{
		id: 22,
		filename: '22.gif',
		src: 'https://gif.plaza.one/22.gif',
		video_src: 'https://gif.plaza.one/mp4/22.mp4',
		author: '',
		author_link: '',
		source: 'Megazone 23',
		source_link: 'https://myanimelist.net/anime/1935/Megazone_23',
		num: '22',
	},
	{
		id: 23,
		filename: '23.gif',
		src: 'https://gif.plaza.one/23.gif',
		video_src: 'https://gif.plaza.one/mp4/23.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '23',
	},
	{
		id: 24,
		filename: '24.gif',
		src: 'https://gif.plaza.one/24.gif',
		video_src: 'https://gif.plaza.one/mp4/24.mp4',
		author: '',
		author_link: '',
		source: 'Urusei Yatsura',
		source_link: 'https://myanimelist.net/anime/1293/Urusei_Yatsura',
		num: '24',
	},
	{
		id: 25,
		filename: '25.gif',
		src: 'https://gif.plaza.one/25.gif',
		video_src: 'https://gif.plaza.one/mp4/25.mp4',
		author: 'peer inward',
		author_link:
			'https://peer-inward.com/post/144175786872/cyber-city-oedo-808-dir-yoshiaki-kawajiri',
		source: 'Cyber City Oedo 808',
		source_link: 'https://myanimelist.net/anime/1352/Cyber_City_Oedo_808',
		num: '25',
	},
	{
		id: 26,
		filename: '26.gif',
		src: 'https://gif.plaza.one/26.gif',
		video_src: 'https://gif.plaza.one/mp4/26.mp4',
		author: '',
		author_link: '',
		source: 'Neon Genesis Evangelion: The End of Evangelion',
		source_link:
			'https://myanimelist.net/anime/32/Neon_Genesis_Evangelion__The_End_of_Evangelion',
		num: '26',
	},
	{
		id: 27,
		filename: '27.gif',
		src: 'https://gif.plaza.one/27.gif',
		video_src: 'https://gif.plaza.one/mp4/27.mp4',
		author: 'kidmograph',
		author_link: 'https://kidmograph.tumblr.com/',
		source: 'Birth of a New Day',
		source_link: 'https://en.wikipedia.org/wiki/Birth_of_a_New_Day',
		num: '27',
	},
	{
		id: 28,
		filename: '28.gif',
		src: 'https://gif.plaza.one/28.gif',
		video_src: 'https://gif.plaza.one/mp4/28.mp4',
		author: '',
		author_link: '',
		source: 'Fate/Zero',
		source_link: 'https://myanimelist.net/anime/10087/Fate_Zero',
		num: '28',
	},
	{
		id: 29,
		filename: '29.gif',
		src: 'https://gif.plaza.one/29.gif',
		video_src: 'https://gif.plaza.one/mp4/29.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '29',
	},
	{
		id: 30,
		filename: '30.gif',
		src: 'https://gif.plaza.one/30.gif',
		video_src: 'https://gif.plaza.one/mp4/30.mp4',
		author: '',
		author_link: '',
		source: 'Tenkuu no Escaflowne',
		source_link: 'https://myanimelist.net/anime/182/Tenkuu_no_Escaflowne',
		num: '30',
	},
	{
		id: 31,
		filename: '31.gif',
		src: 'https://gif.plaza.one/31.gif',
		video_src: 'https://gif.plaza.one/mp4/31.mp4',
		author: 'worldoro',
		author_link: 'http://worldoro.tumblr.com/post/171988593947',
		source: 'Serial Experiments Lain',
		source_link: 'https://myanimelist.net/anime/339/Serial_Experiments_Lain',
		num: '31',
	},
	{
		id: 32,
		filename: '32.gif',
		src: 'https://gif.plaza.one/32.gif',
		video_src: 'https://gif.plaza.one/mp4/32.mp4',
		author: '',
		author_link: '',
		source: 'Cowboy Bebop',
		source_link: 'https://myanimelist.net/anime/1/Cowboy_Bebop',
		num: '32',
	},
	{
		id: 33,
		filename: '33.gif',
		src: 'https://gif.plaza.one/33.gif',
		video_src: 'https://gif.plaza.one/mp4/33.mp4',
		author: '',
		author_link: '',
		source: 'Angel Cop',
		source_link: 'https://myanimelist.net/anime/1351/Angel_Cop',
		num: '33',
	},
	{
		id: 34,
		filename: '34.gif',
		src: 'https://gif.plaza.one/34.gif',
		video_src: 'https://gif.plaza.one/mp4/34.mp4',
		author: '',
		author_link: '',
		source: 'Bishoujo Senshi Sailor Moon',
		source_link:
			'https://myanimelist.net/anime/530/Bishoujo_Senshi_Sailor_Moon',
		num: '34',
	},
	{
		id: 35,
		filename: '35.gif',
		src: 'https://gif.plaza.one/35.gif',
		video_src: 'https://gif.plaza.one/mp4/35.mp4',
		author: '',
		author_link: '',
		source: 'Bishoujo Senshi Sailor Moon',
		source_link:
			'https://myanimelist.net/anime/530/Bishoujo_Senshi_Sailor_Moon',
		num: '35',
	},
	{
		id: 36,
		filename: '36.gif',
		src: 'https://gif.plaza.one/36.gif',
		video_src: 'https://gif.plaza.one/mp4/36.mp4',
		author: '',
		author_link: '',
		source: 'Kimagure Orange\u2606Road',
		source_link:
			'https://myanimelist.net/anime/1087/Kimagure_Orange%24B!y(BRoad',
		num: '36',
	},
	{
		id: 37,
		filename: '37.gif',
		src: 'https://gif.plaza.one/37.gif',
		video_src: 'https://gif.plaza.one/mp4/37.mp4',
		author: '',
		author_link: '',
		source: 'Cowboy Bebop',
		source_link: 'https://myanimelist.net/anime/1/Cowboy_Bebop',
		num: '37',
	},
	{
		id: 38,
		filename: '38.gif',
		src: 'https://gif.plaza.one/38.gif',
		video_src: 'https://gif.plaza.one/mp4/38.mp4',
		author: '',
		author_link: '',
		source: 'Patlabor 2: The Movie',
		source_link:
			'https://myanimelist.net/anime/1096/Kidou_Keisatsu_Patlabor_2_the_Movie',
		num: '38',
	},
	{
		id: 39,
		filename: '39.gif',
		src: 'https://gif.plaza.one/39.gif',
		video_src: 'https://gif.plaza.one/mp4/39.mp4',
		author: 'apollo',
		author_link:
			'https://retroapollo.tumblr.com/post/163104681094/just-let-me-be-free',
		source: '',
		source_link: '',
		num: '39',
	},
	{
		id: 40,
		filename: '40.gif',
		src: 'https://gif.plaza.one/40.gif',
		video_src: 'https://gif.plaza.one/mp4/40.mp4',
		author: '',
		author_link: '',
		source: 'Dragon Ball',
		source_link: 'https://myanimelist.net/anime/223/Dragon_Ball',
		num: '40',
	},
	{
		id: 41,
		filename: '41.gif',
		src: 'https://gif.plaza.one/41.gif',
		video_src: 'https://gif.plaza.one/mp4/41.mp4',
		author: '',
		author_link: '',
		source: 'Kimi ni Todoke',
		source_link: 'https://myanimelist.net/anime/6045/Kimi_ni_Todoke',
		num: '41',
	},
	{
		id: 42,
		filename: '42.gif',
		src: 'https://gif.plaza.one/42.gif',
		video_src: 'https://gif.plaza.one/mp4/42.mp4',
		author: '',
		author_link: '',
		source: 'Rurouni Kenshin: Meiji Kenkaku Romantan',
		source_link:
			'https://myanimelist.net/anime/45/Rurouni_Kenshin__Meiji_Kenkaku_Romantan',
		num: '42',
	},
	{
		id: 43,
		filename: '43.gif',
		src: 'https://gif.plaza.one/43.gif',
		video_src: 'https://gif.plaza.one/mp4/43.mp4',
		author: '',
		author_link: '',
		source: 'Evangelion: 1.0 You Are (Not) Alone',
		source_link:
			'https://myanimelist.net/anime/2759/Evangelion__10_You_Are_Not_Alone',
		num: '43',
	},
	{
		id: 44,
		filename: '44.gif',
		src: 'https://gif.plaza.one/44.gif',
		video_src: 'https://gif.plaza.one/mp4/44.mp4',
		author: '',
		author_link: '',
		source: 'Golden Boy',
		source_link: 'https://myanimelist.net/anime/268/Golden_Boy',
		num: '44',
	},
	{
		id: 45,
		filename: '45.gif',
		src: 'https://gif.plaza.one/45.gif',
		video_src: 'https://gif.plaza.one/mp4/45.mp4',
		author: '',
		author_link: '',
		source: 'Megazone 23',
		source_link: 'https://myanimelist.net/anime/1935/Megazone_23',
		num: '45',
	},
	{
		id: 46,
		filename: '46.gif',
		src: 'https://gif.plaza.one/46.gif',
		video_src: 'https://gif.plaza.one/mp4/46.mp4',
		author: '',
		author_link: '',
		source: 'Roujin Z',
		source_link: 'https://myanimelist.net/anime/2000/Roujin_Z',
		num: '46',
	},
	{
		id: 47,
		filename: '47.gif',
		src: 'https://gif.plaza.one/47.gif',
		video_src: 'https://gif.plaza.one/mp4/47.mp4',
		author: '',
		author_link: '',
		source: 'Byousoku 5 Centimeter',
		source_link: 'https://myanimelist.net/anime/1689/Byousoku_5_Centimeter',
		num: '47',
	},
	{
		id: 48,
		filename: '48.gif',
		src: 'https://gif.plaza.one/48.gif',
		video_src: 'https://gif.plaza.one/mp4/48.mp4',
		author: '',
		author_link: '',
		source: 'Omoide Poroporo',
		source_link: 'https://myanimelist.net/anime/1029/Omoide_Poroporo',
		num: '48',
	},
	{
		id: 49,
		filename: '49.gif',
		src: 'https://gif.plaza.one/49.gif',
		video_src: 'https://gif.plaza.one/mp4/49.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '49',
	},
	{
		id: 50,
		filename: '50.gif',
		src: 'https://gif.plaza.one/50.gif',
		video_src: 'https://gif.plaza.one/mp4/50.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '50',
	},
	{
		id: 51,
		filename: '51.gif',
		src: 'https://gif.plaza.one/51.gif',
		video_src: 'https://gif.plaza.one/mp4/51.mp4',
		author: '',
		author_link: '',
		source: 'Neon Genesis Evangelion',
		source_link: 'https://myanimelist.net/anime/30/Neon_Genesis_Evangelion',
		num: '51',
	},
	{
		id: 52,
		filename: '52.gif',
		src: 'https://gif.plaza.one/52.gif',
		video_src: 'https://gif.plaza.one/mp4/52.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '52',
	},
	{
		id: 53,
		filename: '53.gif',
		src: 'https://gif.plaza.one/53.gif',
		video_src: 'https://gif.plaza.one/mp4/53.mp4',
		author: 'Yasmin Pessoa',
		author_link: 'http://yaspes.tumblr.com',
		source: 'temptation',
		source_link:
			'http://yaspes.tumblr.com/post/159475408342/temptation-inspired-by-my-dreams-of-the-city',
		num: '53',
	},
	{
		id: 54,
		filename: '54.gif',
		src: 'https://gif.plaza.one/54.gif',
		video_src: 'https://gif.plaza.one/mp4/54.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '54',
	},
	{
		id: 55,
		filename: '55.gif',
		src: 'https://gif.plaza.one/55.gif',
		video_src: 'https://gif.plaza.one/mp4/55.mp4',
		author: '',
		author_link: '',
		source: 'Tenchi Muyou!',
		source_link: 'https://myanimelist.net/anime/696/Tenchi_Muyou',
		num: '55',
	},
	{
		id: 56,
		filename: '56.gif',
		src: 'https://gif.plaza.one/56.gif',
		video_src: 'https://gif.plaza.one/mp4/56.mp4',
		author: '',
		author_link: '',
		source: "Cat's Eye",
		source_link: 'https://myanimelist.net/anime/2043/Cats_Eye',
		num: '56',
	},
	{
		id: 57,
		filename: '57.gif',
		src: 'https://gif.plaza.one/57.gif',
		video_src: 'https://gif.plaza.one/mp4/57.mp4',
		author: '',
		author_link: '',
		source: 'Pok\u00e9mon',
		source_link: 'https://myanimelist.net/anime/527/Pokemon',
		num: '57',
	},
	{
		id: 58,
		filename: '58.gif',
		src: 'https://gif.plaza.one/58.gif',
		video_src: 'https://gif.plaza.one/mp4/58.mp4',
		author: '',
		author_link: '',
		source: 'Bubblegum Crisis',
		source_link: 'https://myanimelist.net/anime/1347/Bubblegum_Crisis',
		num: '58',
	},
	{
		id: 59,
		filename: '59.gif',
		src: 'https://gif.plaza.one/59.gif',
		video_src: 'https://gif.plaza.one/mp4/59.mp4',
		author: '',
		author_link: '',
		source: 'Gunnm',
		source_link: 'https://myanimelist.net/anime/1016/Gunnm',
		num: '59',
	},
	{
		id: 60,
		filename: '60.gif',
		src: 'https://gif.plaza.one/60.gif',
		video_src: 'https://gif.plaza.one/mp4/60.mp4',
		author: '',
		author_link: '',
		source: 'Yokohama Kaidashi Kikou',
		source_link: 'https://myanimelist.net/anime/975/Yokohama_Kaidashi_Kikou',
		num: '60',
	},
	{
		id: 61,
		filename: '61.gif',
		src: 'https://gif.plaza.one/61.gif',
		video_src: 'https://gif.plaza.one/mp4/61.mp4',
		author: '',
		author_link: '',
		source: 'Sen to Chihiro no Kamikakushi',
		source_link:
			'https://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi',
		num: '61',
	},
	{
		id: 62,
		filename: '62.gif',
		src: 'https://gif.plaza.one/62.gif',
		video_src: 'https://gif.plaza.one/mp4/62.mp4',
		author: '',
		author_link: '',
		source: 'Nana',
		source_link: 'https://myanimelist.net/anime/877/Nana',
		num: '62',
	},
	{
		id: 63,
		filename: '63.gif',
		src: 'https://gif.plaza.one/63.gif',
		video_src: 'https://gif.plaza.one/mp4/63.mp4',
		author: '',
		author_link: '',
		source: 'Sen to Chihiro no Kamikakushi',
		source_link:
			'https://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi',
		num: '63',
	},
	{
		id: 64,
		filename: '64.gif',
		src: 'https://gif.plaza.one/64.gif',
		video_src: 'https://gif.plaza.one/mp4/64.mp4',
		author: '',
		author_link: '',
		source: 'InuYasha',
		source_link: 'https://myanimelist.net/anime/249/InuYasha',
		num: '64',
	},
	{
		id: 65,
		filename: '65.gif',
		src: 'https://gif.plaza.one/65.gif',
		video_src: 'https://gif.plaza.one/mp4/65.mp4',
		author: '',
		author_link: '',
		source: 'Maison Ikkoku: Ikkokujima Nanpa Shimatsuki',
		source_link:
			'https://myanimelist.net/anime/2459/Maison_Ikkoku__Ikkokujima_Nanpa_Shimatsuki',
		num: '65',
	},
	{
		id: 66,
		filename: '66.gif',
		src: 'https://gif.plaza.one/66.gif',
		video_src: 'https://gif.plaza.one/mp4/66.mp4',
		author: '',
		author_link: '',
		source: 'The Rose of Versailles',
		source_link: 'https://myanimelist.net/anime/338/',
		num: '66',
	},
	{
		id: 67,
		filename: '67.gif',
		src: 'https://gif.plaza.one/67.gif',
		video_src: 'https://gif.plaza.one/mp4/67.mp4',
		author: '',
		author_link: '',
		source: 'Sanctuary',
		source_link: 'https://myanimelist.net/anime/2698/Sanctuary',
		num: '67',
	},
	{
		id: 68,
		filename: '68.gif',
		src: 'https://gif.plaza.one/68.gif',
		video_src: 'https://gif.plaza.one/mp4/68.mp4',
		author: '',
		author_link: '',
		source: 'Twilight Q',
		source_link: 'https://myanimelist.net/anime/1981/',
		num: '68',
	},
	{
		id: 69,
		filename: '69.gif',
		src: 'https://gif.plaza.one/69.gif',
		video_src: 'https://gif.plaza.one/mp4/69.mp4',
		author: '',
		author_link: '',
		source: 'Omoide no Marnie',
		source_link: 'https://myanimelist.net/anime/21557/Omoide_no_Marnie',
		num: '69',
	},
	{
		id: 70,
		filename: '70.gif',
		src: 'https://gif.plaza.one/70.gif',
		video_src: 'https://gif.plaza.one/mp4/70.mp4',
		author: '',
		author_link: '',
		source: 'InuYasha',
		source_link: 'https://myanimelist.net/anime/249/InuYasha',
		num: '70',
	},
	{
		id: 71,
		filename: '71.gif',
		src: 'https://gif.plaza.one/71.gif',
		video_src: 'https://gif.plaza.one/mp4/71.mp4',
		author: '',
		author_link: '',
		source: 'Yuu\u2606Yuu\u2606Hakusho',
		source_link:
			'https://myanimelist.net/anime/392/Yuu%24B!y(BYuu%24B!y(BHakusho',
		num: '71',
	},
	{
		id: 72,
		filename: '72.gif',
		src: 'https://gif.plaza.one/72.gif',
		video_src: 'https://gif.plaza.one/mp4/72.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '72',
	},
	{
		id: 73,
		filename: '73.gif',
		src: 'https://gif.plaza.one/73.gif',
		video_src: 'https://gif.plaza.one/mp4/73.mp4',
		author: '',
		author_link: '',
		source: '',
		source_link: '',
		num: '73',
	},
	{
		id: 74,
		filename: '74.gif',
		src: 'https://gif.plaza.one/74.gif',
		video_src: 'https://gif.plaza.one/mp4/74.mp4',
		author: '',
		author_link: '',
		source: 'Aa! Megami-sama! (TV)',
		source_link: 'https://myanimelist.net/anime/50/Aa_Megami-sama_TV',
		num: '74',
	},
	{
		id: 75,
		filename: '75.gif',
		src: 'https://gif.plaza.one/75.gif',
		video_src: 'https://gif.plaza.one/mp4/75.mp4',
		author: '',
		author_link: '',
		source: 'Yokohama Kaidashi Kikou',
		source_link: 'https://myanimelist.net/anime/975/Yokohama_Kaidashi_Kikou',
		num: '75',
	},
	{
		id: 76,
		filename: '76.gif',
		src: 'https://gif.plaza.one/76.gif',
		video_src: 'https://gif.plaza.one/mp4/76.mp4',
		author: '',
		author_link: '',
		source: 'AD Police',
		source_link: 'https://myanimelist.net/anime/1346/AD_Police',
		num: '76',
	},
	{
		id: 77,
		filename: '77.gif',
		src: 'https://gif.plaza.one/77.gif',
		video_src: 'https://gif.plaza.one/mp4/77.mp4',
		author: 'Robness\u30ed\u30d6\u30cd\u30b9',
		author_link: 'https://twitter.com/RobnessMaximum',
		source: 'Original',
		source_link: 'https://twitter.com/RobnessMaximum',
		num: '77',
	},
	{
		id: 78,
		filename: '78.gif',
		src: 'https://gif.plaza.one/78.gif',
		video_src: 'https://gif.plaza.one/mp4/78.mp4',
		author: 'Robness\u30ed\u30d6\u30cd\u30b9',
		author_link: 'https://twitter.com/RobnessMaximum',
		source: 'Original',
		source_link: 'https://twitter.com/RobnessMaximum',
		num: '78',
	},
	{
		id: 79,
		filename: '79.gif',
		src: 'https://gif.plaza.one/79.gif',
		video_src: 'https://gif.plaza.one/mp4/79.mp4',
		author: 'Robness\u30ed\u30d6\u30cd\u30b9',
		author_link: 'https://twitter.com/RobnessMaximum',
		source: 'Original',
		source_link: 'https://twitter.com/RobnessMaximum',
		num: '79',
	},
	{
		id: 80,
		filename: '80.gif',
		src: 'https://gif.plaza.one/80.gif',
		video_src: 'https://gif.plaza.one/mp4/80.mp4',
		author: 'Robness\u30ed\u30d6\u30cd\u30b9',
		author_link: 'https://twitter.com/RobnessMaximum',
		source: 'Original',
		source_link: 'https://twitter.com/RobnessMaximum',
		num: '80',
	},
	{
		id: 81,
		filename: '81.gif',
		src: 'https://gif.plaza.one/81.gif',
		video_src: 'https://gif.plaza.one/mp4/81.mp4',
		author: 'Robness\u30ed\u30d6\u30cd\u30b9',
		author_link: 'https://twitter.com/RobnessMaximum',
		source: 'Original',
		source_link: 'https://twitter.com/RobnessMaximum',
		num: '81',
	},
	{
		id: 82,
		filename: '82.gif',
		src: 'https://gif.plaza.one/82.gif',
		video_src: 'https://gif.plaza.one/mp4/82.mp4',
		author: 'AxolotlFairy',
		author_link: '',
		source: "JoJo's Bizarre Adventure",
		source_link: 'https://myanimelist.net/anime/666/JoJo_no_Kimyou_na_Bouken',
		num: '82',
	},
	{
		id: 83,
		filename: '83.gif',
		src: 'https://gif.plaza.one/83.gif',
		video_src: 'https://gif.plaza.one/mp4/83.mp4',
		author: '',
		author_link: '',
		source: 'Dirty Pair',
		source_link: 'https://myanimelist.net/anime/424/Dirty_Pair',
		num: '83',
	},
];
